apiVersion: v1
kind: Service
metadata:
  name: cerebro-service
spec:
  type: ClusterIP
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 9000
      name: http
  selector: 
    app: cerebro
  